#!/usr/bin/env python3

# The skel program provides a simple, general-purpose
# generative programming mechanism

from Cheetah.Template import Template
#import json
import sys

from skel import __skel


if __name__=="__main__":
    sys.exit (__skel.main (sys.argv))

